### ISSUE TITLE
Weather JPの情報とるのに失敗して動いてない

### ISSUE THREAD

**Issue by hanachin** [GeekHouseOkinawa/geeokigomi#1]
```
2015-05-09T21:30:21.048324+00:00 heroku[api]: Starting process with command `./geeokigomi.rb` by scheduler@addons.heroku.com
2015-05-09T21:30:24.267786+00:00 heroku[scheduler.9123]: Starting process with command `./geeokigomi.rb`
2015-05-09T21:30:24.872946+00:00 heroku[scheduler.9123]: State changed from starting to up
2015-05-09T21:30:26.833294+00:00 app[scheduler.9123]: /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 403 Forbidden (OpenURI::HTTPError)
2015-05-09T21:30:26.833318+00:00 app[scheduler.9123]:   from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:708:in `buffer_open'
2015-05-09T21:30:26.833320+00:00 app[scheduler.9123]:   from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
2015-05-09T21:30:26.833334+00:00 app[scheduler.9123]:   from /app/vendor/bundle/ruby/2.0.0/gems/weather_jp-1.0.4/lib/weather_jp.rb:117:in `get'
2015-05-09T21:30:26.833333+00:00 app[scheduler.9123]:   from /app/vendor/bundle/ruby/2.0.0/gems/weather_jp-1.0.4/lib/weather_jp.rb:123:in `get_area_code'
2015-05-09T21:30:26.833327+00:00 app[scheduler.9123]:   from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:34:in `open'
2015-05-09T21:30:26.833322+00:00 app[scheduler.9123]:   from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
2015-05-09T21:30:26.833323+00:00 app[scheduler.9123]:   from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
2015-05-09T21:30:26.833324+00:00 app[scheduler.9123]:   from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
2015-05-09T21:30:26.833331+00:00 app[scheduler.9123]:   from /app/vendor/bundle/ruby/2.0.0/gems/weather_jp-1.0.4/lib/weather_jp.rb:130:in `get_xml'
2015-05-09T21:30:26.833335+00:00 app[scheduler.9123]:   from /app/vendor/bundle/ruby/2.0.0/gems/weather_jp-1.0.4/lib/weather_jp.rb:67:in `initialize'
2015-05-09T21:30:26.833326+00:00 app[scheduler.9123]:   from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:688:in `open'
2015-05-09T21:30:26.833337+00:00 app[scheduler.9123]:   from /app/vendor/bundle/ruby/2.0.0/gems/weather_jp-1.0.4/lib/weather_jp.rb:17:in `new'
2015-05-09T21:30:26.833342+00:00 app[scheduler.9123]:   from ./geeokigomi.rb:40:in `<main>'
2015-05-09T21:30:26.833341+00:00 app[scheduler.9123]:   from ./geeokigomi.rb:36:in `message'
2015-05-09T21:30:26.833340+00:00 app[scheduler.9123]:   from ./geeokigomi.rb:32:in `weather'
2015-05-09T21:30:26.833338+00:00 app[scheduler.9123]:   from /app/vendor/bundle/ruby/2.0.0/gems/weather_jp-1.0.4/lib/weather_jp.rb:17:in `get'
2015-05-09T21:30:27.574927+00:00 heroku[scheduler.9123]: Process exited with status 1
2015-05-09T21:30:27.592260+00:00 heroku[scheduler.9123]: State changed from up to complete
```

**Comment by hanachin** [comment]
もうゴミ出すこともないのでHerokuのアプリ消しました... :pray:
